template_path: remote/peer-route-config.yaml
stack_name: peer-nlpsandbox-vpc-admincentral
parameters:
  PeeringConnectionId: pcx-0d02daf67078f046e
  VpcPrivateRouteTable: rtb-076a2da51f9b45fe3
  VpcPublicRouteTable: rtb-0ad3e218e9fadd89c
  VpnCidr: 10.1.0.0/16
hooks:
  before_launch:
    - !cmd "wget {{stack_group_config.aws_infra_templates_root_url}}/v0.2.5/templates/peer-route-config.yaml -N -P templates/remote"
