Parameters:
  RootDomainName:
    Description: Domain name for your website (example.com)
    Type: String
Resources:
  RootBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref RootDomainName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
        RoutingRules:
          - RedirectRule:
              HostName: "www.synapse.org"
              HttpRedirectCode: "307"
              Protocol: https
              ReplaceKeyWith: "#!Synapse:syn22277123/wiki/608544"
            RoutingRuleCondition:
              KeyPrefixEquals: tools/date-annotator/leaderboard
          - RedirectRule:
              HostName: "www.synapse.org"
              HttpRedirectCode: "307"
              Protocol: https
              ReplaceKeyWith: "#!Synapse:syn22277123/wiki/608545"
            RoutingRuleCondition:
              KeyPrefixEquals: tools/person-name-annotator/leaderboard
          - RedirectRule:
              HostName: "www.synapse.org"
              HttpRedirectCode: "307"
              Protocol: https
              ReplaceKeyWith: "#!Synapse:syn22277123/wiki/608546"
            RoutingRuleCondition:
              KeyPrefixEquals: tools/physical-address-annotator/leaderboard
          - RedirectRule:
              HostName: "discord.gg"
              HttpRedirectCode: "307"
              Protocol: https
              ReplaceKeyWith: "Zb4ymtF"
            RoutingRuleCondition:
              KeyPrefixEquals: discord
          - RedirectRule:
              HostName: "docs.google.com"
              HttpRedirectCode: "307"
              Protocol: https
              ReplaceKeyWith: "document/d/15nqxWUqU9pYU4NBuoJaCENBPpIHmjOhW-jhr3UOvHp0/edit?usp=sharing"
            RoutingRuleCondition:
              KeyPrefixEquals: minutes/platform
          - RedirectRule:
              HostName: "www.synapse.org"
              HttpRedirectCode: "307"
              Protocol: https
              ReplaceKeyWith: "nlpsandbox"

  # CNAMEs is not supported by cloudformation
  # TODO: Cloudfront resource has to be manually created.
  # CloudFront:
  #   Type: AWS::CloudFront::Distribution
  #   Properties:
  #     DistributionConfig:
  #       CNAMEs:
  #         - nlpsandbox.io
  #         - www.nlpsandbox.io
  #       Origins:
  #         OriginPath: nlpsandbox.io.s3-website-us-east-1.amazonaws.com
  #       ViewerCertificate:
  #         AcmCertificateArn: arn:aws:acm:us-east-1:841415736403:certificate/f8b759e9-eba1-42ed-b382-1102ca9dac78
  #         MinimumProtocolVersion: TLSv1.2_2018
  #         SslSupportMethod: sni-only
  #       IPV6Enabled: True
  #       Enabled: True

Outputs:
  WebsiteURL:
    Value: !GetAtt RootBucket.WebsiteURL
    Description: URL for website hosted on S3
